version: '3.8'

services:
  app:
    image: maven:3.8.4-openjdk-11
    container_name: fitpeo-automation
    working_dir: /app
    volumes:
      - .:/app
    command: mvn clean install

    environment:
      - MAVEN_OPTS=-Xmx1024m
    networks:
      - fitpeo_network

networks:
  fitpeo_network:
    driver: bridge
